### ISSUE TITLE
Advice about the new advertising machine

### ISSUE THREAD

**Issue by 1-bytes** [kektram/Keks-menu#28]
We noticed that the current advertising machine is finding ads first and then going to crash.
But we can collect the scid of the advertiser and use 2take1 Menu's "join timeout" to block it from entering the room the next time it wants to.

Although this requires grabbing the host, we will have a better way.
Step 1: Enter story mode
Step 2: Open the 2take1 menu panel and set the identity disguise "Change Host Token" to 0
Step 3: Inside the options select Fake Host Token
Step 4: Turn on identity masquerade

Then go back to online mode, you just need to kick out or crash the current host, and you become 100% host of this battlefield yourself :)

Users will no longer see any ads and will not be crashed by others.

**Comment by 1-bytes** [comment]
This is an idea I found in other people's menus, and I am also using it now. I hope I can communicate with you more deeply and add this idea to Kek's menu.

best greetings

**Comment by kektram** [comment]
Okay?
